### ISSUE TITLE
Automatic command alias generation

### ISSUE THREAD

**Issue by Matthewacon** [Wurmcraft/Server-Essentials#11]
Listing every possible string for a command is probably the worst way to register aliases...

**Comment by Wurmatron** [comment]
2abf17a34af233b6bfd2f03f3c2eda28b9a0b6c3

**Comment by Matthewacon** [comment]
I've begun to work on an automated runtime access transformer for both obfuscated and deobfuscated reflection of server and client side classes so that we can replace server side instances of classes with out own implementations. The plan is to use this to replace the default server `CommandHandler` instance, with one that doesn't register command aliases but matches the provided string with a precompiled regex statement, specified by the command or subcommand. This will greatly reduce search times, as there is no data generation involved.
