### ISSUE TITLE
Potential: Command and subcommand API

### ISSUE THREAD

**Issue by Matthewacon** [Wurmcraft/Server-Essentials#23]
Right now all commands are handled through the [EssentialsCommand](https://github.com/Wurmcraft/Server-Essentials/blob/master/src/main/java/wurmcraft/serveressentials/common/commands/EssentialsCommand.java) class, which does not support automated parameter parsing nor subcommands. As of ebaf3e128f1bcc54840adcc5dd5e458d66ce5c5e there are multiple commands that have, in themselves, various subcommands with various functions. I propose that we make a relatively simple and automated Command / Subcommand API to shorten command declarations, simplify code and improve readability. This change would be implemented in tandem with #6 and #9

**Comment by Wurmatron** [comment]
57c10094a935afa292d68a16e59017e598f343b6
