### ISSUE TITLE
Convert the perm class to an enum...

### ISSUE THREAD

**Issue by Matthewacon** [Wurmcraft/Server-Essentials#24]
- Remove all constant variable declarations in the [Perm](https://github.com/Wurmcraft/Server-Essentials/blob/master/src/main/java/wurmcraft/serveressentials/common/reference/Perm.java) class, and replace them with a "nice-'n-condense" enum declaration, whose `Enum#toString()->String` method, simply returns the permission.

**Comment by Wurmatron** [comment]
Fixed ebe1165bd87d701d3c4824783700d52d88e75884
