### ISSUE TITLE
Economy with inflation and banking system

### ISSUE THREAD

**Issue by Matthewacon** [Wurmcraft/Server-Essentials#8]
Open issue to contribute ideas for the economy system.

Current thoughts: 
1) Implement a system of inflation that is proportional to the amount of players on the server, the amount of transactions, etc...

2) Implement an automated banking system with controlled interest rates, adjusted to account for inflation.

3) Have a regional taxation system for teams and claims

4) Make both the inflation and tax systems dependent on player and transaction-capable entity population densities per region

**Comment by Wurmatron** [comment]
e5b6638f51402a1336613c0a527f8209dd039c6e

**Comment by Wurmatron** [comment]
81df279b93ad1afe255d6da195edb96bfe787f0b

**Comment by Wurmatron** [comment]
77c3be26be8e0b315182ab204efd180dd1cea34f

**Comment by Wurmatron** [comment]
e8f8d9d04ff68707ea9151a38fc98ebcffd9693a

**Comment by Wurmatron** [comment]
Invalidated Due To Post-Rest-Rework
