### ISSUE TITLE
Tab auto-completion

### ISSUE THREAD

**Issue by Matthewacon** [Wurmcraft/Server-Essentials#9]
1) Tab autocomplete commands from partial string
2) Tab autocomplete for parameters such as: Home locations, Playernames / Nicknames, Warps, etc...

Commands in need of tab auto-completion:
`Tp, tpa, warp, home, delhome, vault, team, reloadplayerdata, invsee, onlinetime, seen, heal, gamemode, freeze, fly, echest, delplayerfile, senditem, kit, pay, spy, mute, MSG, channel, teamadmin, sudo, setgroup, delwa`

**Comment by Matthewacon** [comment]
We should also account for misspelled names and words. We could implement a "percentage of correctness" system where the supplied characters are compared to that of each username and a percentage of how many characters were identical, is given. Using this we could predict each auto corrected username with greater accuracy.

If we decide to be ridiculous, we can also create a gradient for the possibility of pressing a key that is relatively close to the intended key and use this to further the above percentage. But that's a bit extreme, especially for Minecraft

**Comment by Wurmatron** [comment]
Basic Completion 6884b9ca23a0080817d41b0c73a4c0a736bae5ec
